#
# Macro file for TestEm11
#
# limit the step size from histo 1
#
/control/cout/ignoreThreadsExcept 0
/control/verbose 2
/run/verbose 1
#
/testem/det/setNbOfAbsor  1
/testem/det/setAbsor 1 plexiglass  500 mm
/testem/det/setSizeYZ 100 mm
#

#/globalField/setValue 0. 1. 0. tesla

/testem/phys/addPhysics  local# em physics
#/testem/phys/emstandard_opt0
#/testem/phys/addPhysics LBE

# Hadronic physics (for neutron production)

###/testem/phys/addPhysics  empenelope  	# em physics 
#
/run/initialize

#
/testem/gun/setDefault
/gun/particle e-
/gun/energy 9 MeV


#
#/analysis/setFileName VHEE
#/analysis/h1/set 1 100 0.    600. mm
#/analysis/h1/set 2 102 0. 160. MeV	
#/analysis/h1/set 3 100 0.    2. mm	
#/analysis/h1/set 4  10 0.   20. um	
#/analysis/h1/set 5 100 0.    300. mm	
##
/testem/applyAutomaticStepMax false
#
/run/printProgress 10000
/run/beamOn 1000000